import { Transaction } from './types';

export const INITIAL_TRANSACTIONS: Transaction[] = [];

export const CATEGORIES = [
  '租金 Rental Fee',
  '廣告費 Advertising Fees',
  '電費 Electricity For Office',
  '公司用品 Supplies Expenses',
  '管理費 Management Fees',
  '網絡費 Internet Service',
  '現金 Cash',
  '銀行手續費 Bank Charge',
  '薪金 SALARY',
  '銷售 Sales',
  '其他 Others'
];

export const TRANSLATIONS = {
  en: {
    appTitle: 'FinReport',
    report: 'Report',
    analysis: 'Analysis',
    totalIncome: 'Total Income',
    totalExpense: 'Total Expenses',
    netIncome: 'Net Income',
    smartEntryTitle: 'Smart Assistant',
    smartEntryHint: 'Type naturally, e.g., "Lunch 500" or "Received 5000 deposit". Works offline.',
    smartEntryPlaceholder: 'e.g., Taxi 200...',
    smartEntryButton: 'Analyze',
    addTransactionTitle: 'Add Transaction',
    date: 'Date',
    type: 'Type',
    income: 'Income',
    expense: 'Expense',
    category: 'Category',
    description: 'Description',
    amount: 'Amount (HKD)',
    addRecord: 'Add Record',
    monthlyLedger: 'Monthly Ledger',
    noRecords: 'No records found. Add a transaction to begin.',
    total: 'Total',
    expenseBreakdown: 'Expense Breakdown',
    dailyCashFlow: 'Daily Cash Flow',
    deleteTitle: 'Delete Record',
    errorSmart: 'Could not detect an amount. Please try again.',
    startDate: 'Start Date',
    endDate: 'End Date',
    filter: 'Filter',
    clearFilter: 'Clear',
    exportPDF: 'Export PDF / Print',
    printHeader: 'Financial Monthly Report',
    period: 'Period',
    backup: 'Backup Data',
    restore: 'Restore Data',
    restoreConfirm: 'This will overwrite your current data. Are you sure?',
    importSuccess: 'Data restored successfully!',
    importError: 'Invalid data file.',
    others: 'Others',
    sortDate: 'Sort Date',
    sortAsc: 'Oldest First',
    sortDesc: 'Newest First',
  },
  zh: {
    appTitle: '財務報表',
    report: '報表',
    analysis: '分析',
    totalIncome: '總收入',
    totalExpense: '總支出',
    netIncome: '淨收入',
    smartEntryTitle: '智能記賬助手',
    smartEntryHint: '支援中英文，例如「午餐 500元」或「收到訂金 5000」。香港本地運算，無需 VPN。',
    smartEntryPlaceholder: '例如：的士 200...',
    smartEntryButton: '智能分析',
    addTransactionTitle: '新增交易',
    date: '日期',
    type: '類型',
    income: '收入',
    expense: '支出',
    category: '項目類別',
    description: '說明',
    amount: '金額 (HKD)',
    addRecord: '新增記錄',
    monthlyLedger: '月度報表',
    noRecords: '暫無記錄。請新增交易。',
    total: '總計',
    expenseBreakdown: '支出分佈',
    dailyCashFlow: '每日現金流',
    deleteTitle: '刪除記錄',
    errorSmart: '無法識別金額，請確保輸入包含數字。',
    startDate: '開始日期',
    endDate: '結束日期',
    filter: '篩選',
    clearFilter: '清除',
    exportPDF: '匯出 PDF / 列印',
    printHeader: '財務月度報表',
    period: '報表週期',
    backup: '備份數據 (下載)',
    restore: '還原數據 (上傳)',
    restoreConfirm: '這將覆蓋現有的所有數據。確定要還原嗎？',
    importSuccess: '數據已還原！已清除日期篩選以顯示所有數據。',
    importError: '無效的數據文件。',
    others: '其他 (Others)',
    sortDate: '日期排序',
    sortAsc: '日期 (舊→新)',
    sortDesc: '日期 (新→舊)',
  }
};